web:
  port: 8091

ui:
  title: "krisyotam.com Status"
  header: "Status"
  description: "Service status for krisyotam.com"
  logo: "https://krisyotam.com/favicon.png"

storage:
  type: sqlite
  path: /data/status.db

endpoints:
  - name: krisyotam.com
    group: websites
    url: "https://krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: notes.krisyotam.com
    group: websites
    url: "https://notes.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: videos.krisyotam.com
    group: websites
    url: "https://videos.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: git.krisyotam.com
    group: websites
    url: "https://git.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: gist.krisyotam.com
    group: websites
    url: "https://gist.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: shop.krisyotam.com
    group: websites
    url: "https://shop.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: photos.krisyotam.com
    group: websites
    url: "https://photos.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"
