web:
  port: 8090

ui:
  title: "krisyotam.com Status"
  header: "Status"
  description: "Service status for krisyotam.com"
  logo: "https://krisyotam.com/favicon.ico"

storage:
  type: sqlite
  path: /data/status.db

endpoints:
  - name: krisyotam.com
    group: websites
    url: "https://krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: notes.krisyotam.com
    group: websites
    url: "https://notes.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: videos.krisyotam.com
    group: websites
    url: "https://videos.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: git.krisyotam.com
    group: websites
    url: "https://git.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: gist.krisyotam.com
    group: websites
    url: "https://gist.krisyotam.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: Domain Expiration
    group: dns
    url: "https://krisyotam.com"
    interval: 1h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: DNS Resolution
    url: "8.8.8.8"
    group: dns
    interval: 5m
    dns:
      query-name: "krisyotam.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
