services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus-kris
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - gatus-data:/data
    labels:
      sg.owner: "kris"
      sg.service-type: "gatus"
      sg.service-group: "monitoring"
      sg.subdomain: "status.krisyotam.com"
    environment:
      - GATUS_PORT=8090

volumes:
  gatus-data:
